# Generated by Django 3.0.3 on 2020-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0004_auto_20200629_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='id_modelo',
            field=models.IntegerField(),
        ),
    ]
