# Generated by Django 3.0.3 on 2020-06-30 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merlindjango', '0007_auto_20200629_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSMModels',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('organismo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=500)),
                ('artigo', models.TextField()),
                ('ano', models.IntegerField()),
                ('sbml', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Models',
        ),
    ]
