# Generated by Django 3.0.3 on 2020-07-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merlindjango', '0008_auto_20200630_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmmodels',
            name='ano',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gsmmodels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
