# Generated by Django 3.0.3 on 2020-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0014_auto_20200708_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsmmodels',
            name='is_public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
