# Generated by Django 3.0.3 on 2020-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0015_gsmmodels_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsmmodels',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
