# Generated by Django 3.0.3 on 2020-07-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0016_auto_20200708_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmmodels',
            old_name='sbml',
            new_name='ficheiro',
        ),
        migrations.RemoveField(
            model_name='gsmmodels',
            name='autor',
        ),
    ]
