# Generated by Django 3.0.3 on 2020-07-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0017_auto_20200708_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='autor',
        ),
    ]
