# Generated by Django 3.0.3 on 2020-07-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0020_auto_20200712_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadablefiles',
            options={'verbose_name_plural': 'Downloads'},
        ),
    ]
