# Generated by Django 3.0.3 on 2020-07-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0021_auto_20200712_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadablefiles',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Downloads'},
        ),
    ]
