# Generated by Django 3.0.3 on 2020-07-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0023_auto_20200717_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmmodels',
            old_name='nome',
            new_name='name',
        ),
    ]
