# Generated by Django 3.0.3 on 2020-07-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0024_auto_20200718_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmmodels',
            old_name='organismo',
            new_name='organism',
        ),
    ]
