# Generated by Django 3.0.3 on 2020-07-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0026_auto_20200718_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmmodels',
            old_name='ano',
            new_name='year',
        ),
    ]
