# Generated by Django 3.0.3 on 2020-07-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlindjango', '0027_auto_20200718_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gsmmodels',
            old_name='ficheiro',
            new_name='file',
        ),
    ]
